### ISSUE TITLE
Errors in SynExportHTML

### ISSUE THREAD

**Issue by groehner** [pyscripter/SynEdit#65] opened 2023-05-27 18:57 UTC
If I export this source code to HTML
![grafik](https://github.com/pyscripter/SynEdit/assets/53400267/aea8ce00-fe97-41cd-a10f-70a35a16d64f)
I get this result:
![grafik](https://github.com/pyscripter/SynEdit/assets/53400267/1674a7ff-7f45-4485-8245-47da803b5d09)
As you can see, only the first command has the right font and lot of empty lines are missing.

The W3C.org HTML Validator shows this error:
Error: Stray end tag div.
From line 20, column 28233; to line 20, column 28238
<br></div></div>↩</body>

The html inspector of a browser developer tool shows, that the font is only applied to the first comment.
![grafik](https://github.com/pyscripter/SynEdit/assets/53400267/8b12cbef-ebc6-482b-92fc-b0ea332f92b1)

It's inappropriate to use <div> elements. The HTML documentation says:
The <div> HTML element is the generic container for flow content. It has no effect on the content or layout until styled in some way using CSS (e.g. styling is directly applied to it, or some kind of layout model like Flexbox is applied to its parent element). 
As a "pure" container, the <div> element does not inherently represent anything. Instead, it's used to group content so it can be easily styled using the class or id attributes, marking a section of a document as being written in a different language (using the lang attribute), and so on. 
But SynExportHTML doesn't style the <div> elements.

HTML has elements to handle with source code. <code> and <samp> are used to render short soure code pieces.
For a whole python program the <pre> element is appropiate. The HTML documentation says:
The <pre> HTML element represents preformatted text which is to be presented exactly as written in the HTML file. The text is typically rendered using a non-proportional, or monospaced, font. Whitespace inside this element is displayed as written. 
If you have to display reserved characters such as <, >, &, and " within the <pre> tag, the characters must be escaped using their respective HTML entity. 

For these reasons I prepared a new version of SynExportHTML, which uses the <pre> element and no <div> elements. The W3C Validator shows no longer shows error. I try to make a pull request for the SynExportHTML.

**Comment by groehner** [comment] 2023-05-27 19:01
Sorry, I wasn't aware, that I get problems with concrete html elements, like `<div>` , `<pre>`, `<code>`. So the comment before is a little bit messed up.

**Comment by groehner** [comment] 2023-05-27 19:06
I wanted to say this:

It's inappropriate to use `<div>` elements. The HTML documentation says:
The `<div>` HTML element is the generic container for flow content. It has no effect on the content or layout until styled in some way using CSS (e.g. styling is directly applied to it, or some kind of layout model like Flexbox is applied to its parent element).
As a "pure" container, the `<div>` element does not inherently represent anything. Instead, it's used to group content so it can be easily styled using the class or id attributes, marking a section of a document as being written in a different language (using the lang attribute), and so on.
But SynExportHTML doesn't style the `<div>` elements.

HTML has elements to handle with source code.  `<code>` and  `<samp>` are used to render short soure code pieces.
For a whole python program the `<pre>` element is appropiate. The HTML documentation says:
The `<pre>`  HTML element represents preformatted text which is to be presented exactly as written in the HTML file. The text is typically rendered using a non-proportional, or monospaced, font. Whitespace inside this element is displayed as written.
If you have to display reserved characters such as <, >, &, and " within the `<pre>`  tag, the characters must be escaped using their respective HTML entity.


For these reasons I prepared a new version of SynExportHTML, which uses the `<pre>`  element and no 
`<div>` elements. The W3C Validator shows no longer shows error. I try to make a pull request for the SynExportHTML.

**Comment by pyscripter** [comment] 2023-05-28 12:56
Thanks.  Please do.
Is this related to #63?

**Comment by pyscripter** [comment] 2023-05-28 16:34
@MShark67 Any views on this?

**Comment by pyscripter** [comment] 2023-06-02 21:08
@groehner Could you please check whether the issue is now resolved?  If yes please close the issue.

**Comment by groehner** [comment] 2023-06-03 16:26
The issues are now resolved. The font is correct for the whole file and no empty lines are missing.

The W3C HTML validator shows these warnings and errors:
![grafik](https://github.com/pyscripter/SynEdit/assets/53400267/8fd2e095-49b0-4d2f-b04e-3a2f0d6a43f5)


Error 2 can be fixed with:

  HeadStartText = '<head>' + sLineBreak + '<meta charset="utf-8">' + sLineBreak;

Error 3 can be fixed with:

  DocType       = '<!DOCTYPE html>' + sLineBreak;    
Header := DocType + Header +  HeadStartText; // in getHeader 
Warning 4: StyleStartText = '<style>'#13#10 +

Others: white-space: pre; is obsolete 

In the html source code the whole div structure is just one line. for my test file with 120 python lines it is 33842 chars long. This is impractical do work with. Possible work around: don't use "white-space: pre;" and follow every `<br>` with a sLineBreak

**Comment by pyscripter** [comment] 2023-06-03 18:44
I have implemented all your suggestions + added character encoding info.
Please check one last time.

**Closed as completed** 2023-06-03 18:43 UTC

**Comment by groehner** [comment] 2023-06-03 19:49
I checked it. Everything is ok!

You changed #13#10 to sLineBreak in the DetailSection. 
I suppose that on Mac this can conflict with DetailLength = 105.

**Comment by pyscripter** [comment] 2023-06-03 20:31
> I suppose that on Mac this can conflict with DetailLength = 105.

@groehner I like your attention to detail!!  Fixed.

**Comment by JaFi-cz** [comment] 2023-06-04 05:43
I am sorry, but it doesn't work with background color.
To simulate:
use some dark background
select part of code (don't export whole file)
copy to clipboard
paste into desktop word or simply see the result as HTML

There is no info about background

**Comment by pyscripter** [comment] 2023-06-04 09:36
@JaFi-cz 
Works here:

Word:
![image](https://github.com/pyscripter/SynEdit/assets/1311616/173ea649-dabc-44e3-b30b-ccb3a1dbfd4b)

Thunderbird:
![image](https://github.com/pyscripter/SynEdit/assets/1311616/f36b5b38-4fd0-42da-bc6a-fdeaa70a8149)

but I am seeing a problem with dark background.   I am looking into this.

**Comment by pyscripter** [comment] 2023-06-04 09:54
@JaFi-cz Fixed.

Thanks for finding and reporting it.
Please try again.

**Comment by JaFi-cz** [comment] 2023-06-04 10:47
Fix confirmed, thank you
